version: "3"

services:
  pangea_ui:
    restart: always
    build: 
      context: ./
      dockerfile: ./.docker/Dockerfile.webapp
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  pangea_service:
    restart: always
    build: 
      context: ./
      dockerfile: ./.docker/Dockerfile.service
    ports:
      - 8000:8000
    command: bash -c "uvicorn main:app --reload --port 8000 --host 0.0.0.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"